dwsurvey:
  site: 'local'
  web:
    file-path: dwfile/dwsurvey/
    static-type: static
    site-url: http://localhost:8081
    #    site-url: http://ent82.surveyform.cn
    info:
      site-name: 调问网
      site-url: http://www.diaowen.net
      site-icp: 京ICP备13050030号-3
      site-mail: service@diaowen.net
      site-phone: 18888888888
  weixin:
    app-id: xxx
    app-secret: xxx
    server:
      token: xxx
      encodingAESKey:
  version:
    info: DWSurvey OSS V5.0 Boot
    number: OSS V5.0
    built: 2021/11/21
server:
  port: 8081

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${dwsurvey.web.file-path}
  #       static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/public/,file:${dwsurvey.web.file-path}

  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/dwsurvey?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456,.
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      # naming:
      #  implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl #指定jpa的自动表生成策略，驼峰自动映射为下划线格式
    properties:
      hibernate:
        #是否自动打印hql对应的sql语句
        show_sql: false
        #是否格式化sql语句
        format_sql: false
        #事务交由spring管理
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        #        enable_lazy_load_no_trans: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
logging:
  level:
    net:
      diaowen: INFO
    org:
      hibernate: ERROR
      apache: ERROR
